# Generated by Django 4.2.29 on 2026-04-08 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import scheduling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(validators=[scheduling.models.validate_appointment_schedule_date])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='person.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='person.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(validators=[scheduling.models.validate_appointment_schedule_date])),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil change'), ('tire_change', 'Tire change'), ('inspection', 'Inspection'), ('brake_service', 'Brake service'), ('diagnostics', 'Diagnostics'), ('battery_replacement', 'Battery replacement'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to='person.customer')),
            ],
        ),
    ]
