# Generated by Django 4.2.29 on 2026-05-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDrive',
        ),
    ]
