# Generated by Django 4.2.29 on 2026-04-08 13:02

import django.core.validators
from django.db import migrations, models
import person.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Name can contain only letters.', regex='^[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]+$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can contain only letters.', regex='^[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL')),
                ('address', models.TextField(validators=[django.core.validators.MinLengthValidator(8)])),
                ('date_of_birth', models.DateField(validators=[person.models.validate_birth_date])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Name can contain only letters.', regex='^[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]+$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can contain only letters.', regex='^[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL')),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('admin', 'Admin')], default='worker', max_length=10)),
                ('hire_date', models.DateField(validators=[person.models.validate_hire_date])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
