# Generated by Django 4.2.29 on 2026-05-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='layoff_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
