# Generated by Django 4.2.29 on 2026-05-15 09:45

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_employee_employment_status_employee_layoff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='layoff_date',
            field=models.DateField(blank=True, null=True, validators=[person.models.validate_no_future_date]),
        ),
    ]
