# Generated by Django 4.2.29 on 2026-04-08 13:02

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40, null=True)),
                ('vehicel_type', models.CharField(max_length=40, null=True)),
                ('year', models.PositiveIntegerField(validators=[cars.models.year_validator])),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid VIN format.', regex='^[A-HJ-NPR-Z0-9]{17}$')])),
                ('mileage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000000)])),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=10)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
