# Generated by Django 4.2.29 on 2026-04-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='vehicel_type',
            new_name='vehicle_type',
        ),
    ]
