# Generated by Django 4.2.29 on 2026-04-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='purchease_price',
            new_name='purchase_price',
        ),
    ]
