# Generated by Django 4.2.29 on 2026-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_purchease_price_cars_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
