# Generated by Django 4.2.29 on 2026-05-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_employee_layoff_date'),
        ('cars', '0002_car_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bought_cars', to='person.customer'),
        ),
    ]
