# Generated by Django 4.2.29 on 2026-04-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_color_alter_car_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('wagon', 'Wagon'), ('convertible', 'Convertible'), ('van', 'Van'), ('pickup', 'Pickup')], max_length=20),
        ),
    ]
