# Generated by Django 4.2.29 on 2026-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
    ]
