# Generated by Django 4.2.29 on 2026-04-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
