# Generated by Django 4.2.29 on 2026-04-02 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_cars_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid VIN format.', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
    ]
