# Generated by Django 4.2.29 on 2026-05-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_fuel_type_car_transmission_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='transmission_type',
            new_name='transmission',
        ),
    ]
