# Generated by Django 4.2.29 on 2026-05-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_employee_layoff_date'),
        ('cars', '0005_rename_transmission_type_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='listing_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='person.customer'),
        ),
    ]
