# Generated by Django 4.2.29 on 2026-04-04 11:22

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_cars_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000000)]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(validators=[cars.models.year_validator]),
        ),
    ]
