# Generated by Django 4.2.29 on 2026-04-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_cars_description_alter_cars_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='vehicel_type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
