# Generated by Django 4.2.29 on 2026-04-06 07:09

import customers.models
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Name can contain only letters.', regex='^[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]+$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can contain only letters.', regex='^[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL')),
                ('address', models.TextField(validators=[django.core.validators.MinLengthValidator(8)])),
                ('date_of_birth', models.DateField(validators=[customers.models.validate_birth_date])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
