from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import TokenRefreshView
from cars.views.api_views import (
    CarRegistrationView,
    CarDetailUpdateView,
    AllCarsDetailView,
    CarSoftDeleteView,
    CarModerationStatusUpdateViewApproved,
    CarModerationStatusUpdateViewRejected,
    CarPurchaseStatusUpdateViewSold,
    CarPurchaseStatusUpdateViewReserved,
    OwnerOrStaffOrSuperuserAllCarsDetailView,
    CarDetailForSoftDeleteView,
    )
from person.views.api_views import (
    CustomerDetailView,
    CustomerListView,
    CustomerRegistrationView,
    EmployeeRegistrationView,
    EmployeeListView,
    EmployeeDetailView,
    ChangePasswordView,
    AdminEmployeeUpdateView,
    AdminEmployeeEmploymentStatusUpdateView,
    EmployeeLoginView,
    CustomerLoginView,
)
from sales.views.api_views import (
    SaleRegistrationView,
    BuyerSalesListView,
    OwnerSalesListView,
    StaffSalesListView,
)

router = routers.DefaultRouter()

urlpatterns = [
    # API urls
    # Authentication urls
    path(
        "",
        include(router.urls)
        ),
    path(
        "api-auth/",
        include("rest_framework.urls",
        namespace="rest_framework")
        ),
    path(
        "employee/token/",
        EmployeeLoginView.as_view(),
        name="employee-token-obtain-pair"
        ),
    path(
        "customer/token/",
        CustomerLoginView.as_view(),
        name="customer-token-obtain-pair"
        ),
    path(
        "employee/token/refresh/",
        TokenRefreshView.as_view(),
        name="employee-token-refresh"
        ),
    # Customers urls
    path(
        "register/customer/",
        CustomerRegistrationView.as_view(),
        name="customer-registration"
        ),
    path(
        "customer/me/",
        CustomerDetailView.as_view(),
        name="customer-detail"
        ),
    path(
        "customers/",
        CustomerListView.as_view(),
        name="customer-list"
        ),
    path(
        "change-password/",
        ChangePasswordView.as_view(),
        name="change-password"
        ),
    # Employees urls
    path(
        "employee/me/",
        EmployeeDetailView.as_view(),
        name="employee-detail"
        ),
    path(
        "register/employee/",
        EmployeeRegistrationView.as_view(),
        name="employee-registration"
        ),
    path(
        "admin/employees/",
        EmployeeListView.as_view(),
        name="employee-list"
        ),
    path(
        "admin/employees/<int:pk>/",
        AdminEmployeeUpdateView.as_view(),
        name="admin-employee-update"
        ),
    path(
        "admin/employees/<int:pk>/employment-status/",
        AdminEmployeeEmploymentStatusUpdateView.as_view(),
        name="admin-employee-employment-status-update"
        ),
    # Cars urls
    path(
        "register/car/",
        CarRegistrationView.as_view(),
        name="car-registration"
        ),
    path(
        "cars/<int:pk>/update/",
        CarDetailUpdateView.as_view(),
        name="car-detail-update"
        ),
    path(
        "cars/not-approved/<int:pk>/",
        OwnerOrStaffOrSuperuserAllCarsDetailView.as_view(),
        name="car-detail-not-approved"
        ),
    path(
        "cars/approved/<int:pk>/",
        AllCarsDetailView.as_view(),
        name="car-detail-approved"
        ),
    path(
        "cars/soft-deleted/<int:pk>/",
        CarDetailForSoftDeleteView.as_view(),
        name="car-detail-soft-deleted"
        ),
    path(
        "cars/soft-delete/<int:pk>/",
        CarSoftDeleteView.as_view(),
        name="car-soft-delete"
        ),
    path(
        "cars/<int:pk>/moderation-status/approved/",
        CarModerationStatusUpdateViewApproved.as_view(),
        name="car-moderation-status-update-approved"
        ),
    path(
        "cars/<int:pk>/moderation-status/rejected/",
        CarModerationStatusUpdateViewRejected.as_view(),
        name="car-moderation-status-update-rejected"
        ),
    path(
        "cars/<int:pk>/purchase-status/sold/",
        CarPurchaseStatusUpdateViewSold.as_view(),
        name="car-purchase-status-update-sold"
        ),
    path(
        "cars/<int:pk>/purchase-status/reserved/",
        CarPurchaseStatusUpdateViewReserved.as_view(),
        name="car-purchase-status-update-reserved"
        ),
    path(
        "sales/cars/<int:pk>/register/",
        SaleRegistrationView.as_view(),
        name="sale-car-registration"
        ),
    path(
        "sales/buyer/list/",
        BuyerSalesListView.as_view(),
        name="buyer-sales-list"
        ),
    path(
        "sales/owner/list/",
        OwnerSalesListView.as_view(),
        name="owner-sales-list"
        ),
    path(
        "sales/staff/list/",
        StaffSalesListView.as_view(),
        name="staff-sales-list"
        ),
]