from django.urls import path
from person.views.template_views import (
    customer_registration_view,
    login_view,
    customer_profile_view,
    customer_profile_update_view,
    password_change_view,
    employee_profile_view,
    employee_list_view,
    admin_employee_update_view
)

urlpatterns = [
    path(
        "register/customer/form/",
        customer_registration_view,
        name="customer-registration-form"
    ),
    path(
        "login/customer/form/",
        login_view,
        name="customer-login-form"
    ),
    path(
        "customer/profile/",
        customer_profile_view,
        name="customer-profile"
    ),
    path(
        "customer/profile/update/",
        customer_profile_update_view,
        name="customer-profile-update"
    ),
    path(
        "user/change-password/",
        password_change_view,
        name="user-change-password"
    ),
    path(
        "employee/profile/",
        employee_profile_view,
        name="employee-profile"
    ),
    path(
        "employee/list/",
        employee_list_view,
        name="employee-list"
    ),
    path(
        "employee/update/<int:pk>/",
        admin_employee_update_view,
        name="admin-employee-update-template"
    )
]