from django.urls import path
from person.views.template_views import (
    admin_employee_employment_status_update_view,
    customer_registration_view,
    customer_list_view,
    login_view,
    customer_profile_view,
    customer_profile_update_view,
    password_change_view,
    employee_profile_view,
    employee_list_view,
    admin_employee_update_view,
    admin_employee_registration_view,
    logout_view
)
from cars.views.template_views import (
    customer_car_registration_view,
    public_car_list_view,
    owner_car_list_view,
    employee_deleted_cars_list_view,
    employee_car_moderation_list_view,
    employee_car_moderation_update_approved_view,
    employee_car_moderation_update_rejected_view,
    owner_car_update_view,
    owner_and_staff_car_soft_delete_view
)
from sales.views.template_views import (
    customer_sale_registration_view,
)

urlpatterns = [
    path(
        "register/customer/form/",
        customer_registration_view,
        name="customer-registration-form"
    ),
    path(
        "login/form/",
        login_view,
        name="login-form"
    ),
    path(
        "customer/profile/",
        customer_profile_view,
        name="customer-profile"
    ),
    path(
        "customer/profile/update/",
        customer_profile_update_view,
        name="customer-profile-update"
    ),
    path(
        "user/change-password/",
        password_change_view,
        name="user-change-password"
    ),
    path(
        "employee/profile/",
        employee_profile_view,
        name="employee-profile"
    ),
    path(
        "employee/list/",
        employee_list_view,
        name="employee-list-template"
    ),
    path(
        "employee/update/<int:pk>/",
        admin_employee_update_view,
        name="admin-employee-update-template"
    ),
    path(
        "employee/admin/employees/<int:pk>/employment-status/update/",
        admin_employee_employment_status_update_view,
        name="admin-employee-employment-status-update-template"
    ),
    path(
        "employee/admin/employees/register/",
        admin_employee_registration_view,
        name="admin-employee-registration-template"
    ),
    path(
        "logout/",
        logout_view,
        name="logout"
        ),
    path(
        "customer/list/",
        customer_list_view,
        name="customer-list-template"
    ),
    path(
        "customer/car/register/",
        customer_car_registration_view,
        name="customer-car-registration-template"
    ),
    path(
        "public/cars/",
        public_car_list_view,
        name="public-car-list-template"
    ),
    path(
        "me/cars/",
        owner_car_list_view,
        name="owner-cars-list-template"
    ),
    path(
        "employee/deleted/cars/",
        employee_deleted_cars_list_view,
        name="employee-deleted-cars-list-template"
    ),
    path(
        "employee/car/moderation/list/",
        employee_car_moderation_list_view,
        name="employee-car-moderation-list-template"
    ),
    path(
        "employee/car/moderation/update/<int:pk>/",
        employee_car_moderation_update_approved_view,
        name="employee-car-moderation-update-approved-template"
    ),
    path(
        "employee/car/moderation/update/<int:pk>/rejected/",
        employee_car_moderation_update_rejected_view,
        name="employee-car-moderation-update-rejected-template"
    ),
    path(
        "employee/car/action/update/<int:pk>/softdelete/",
        owner_and_staff_car_soft_delete_view,
        name="employee-car-action-update-softdelete-template"
    ),
    path(
        "customer/car/action/update/<int:pk>/softdelete/",
        owner_and_staff_car_soft_delete_view,
        name="customer-car-action-update-softdelete-template"
    ),
    path(
        "me/cars/update/<int:pk>/",
        owner_car_update_view,
        name="owner-car-update-template"
    ),
    path(
        "customer/sale/register/<int:pk>/",
        customer_sale_registration_view,
        name="sale-car-registration-template"
    ),
]