# Generated by Django 4.2.29 on 2026-06-16 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_car_buyer'),
        ('person', '0003_alter_employee_layoff_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('transaction_number', models.CharField(max_length=20, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('transfer', 'Transfer'), ('leasing', 'Leasing')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bought_cars_sales', to='person.customer')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='cars.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_cars_sales', to='person.customer')),
            ],
        ),
    ]
