# Generated by Django 4.2.29 on 2026-06-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_created_at_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
