# Generated by Django 4.2.29 on 2026-06-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_buyer'),
        ('sales', '0003_alter_sale_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cars.car'),
        ),
    ]
